version: "3.8"

services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend
  
  frontend:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - backend